# Generated by Django 5.1.2 on 2024-10-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='carimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
